### ISSUE TITLE
Castling does not detect friendly piece collision

### ISSUE THREAD

**Issue by LupoCani** [existentialcomics/kungFuChess#16]
In the replay of <https://www.kungfuchess.org/game/138739>, we see the black king and queen simultaneously occupy g8 on replay. When I played this game, I believe it instead looked like the black queen moved directly from g8 to e2, nightrider-style.

Currently unable to reproduce.

**Comment by LupoCani** [comment]
Reproduced at <https://kungfuchess.org/game/138757>. On closer inspection it would appear the collision checking doesn't properly handle castling.

Additionally, replay sometimes shows the black king remaining at g8 for the entire game, which then ends inexplicably when the rook moves to (actually capturing the king at) e3. Unable to reproduce this, unclear if it's related.

**Comment by LupoCani** [comment]
Reproduced with the player pieces.

<https://kungfuchess.org/game/138758>

Steps to reproduce (for white):
* Do not move the queen.
* Short castle.
* With the king and rook in motion, move the queen to g1.

Expected behaviour: The queen is killed, or fails to reach the square.

Observed behaviour: The queen and king simultaneously occupy g1. The queen is unable to be moved for the remainder of the game.

**Comment by LupoCani** [comment]
Possibly fixed as of 2024-02-25, but there may remain an issue where (after following the steps to reproduce) the queen ends up on e1, but is unable to move for the remainder of the game. This has only been observed once (<https://kungfuchess.org/game/140904>) and never reproduced, to my knowledge. Further testing is needed.

**Comment by LupoCani** [comment]
Here's a replication.

<https://kungfuchess.org/game/140931>

* Black tries to overlap-castle but fails due to the fix, which is correct behavior. The black queen then moves once, which is also correct.
* The black queen then becomes immune to capture while remaining stationary for the remainder of the game, with both the pieces that would have landed on its square spontaneously being killed on contact instead.
* Pieces on adjacent squares were also unable to even begin a move to capture the queen, and the rook (but not the promoted white queen) became impossible move after being moved away from the black queen.

**Comment by LupoCani** [comment]
This may not be precisely a replication, after all.

<https://www.kungfuchess.org/game/140956>

As it stands, at least any white piece moved onto b1 becomes immovable and immune from capture, including the king, breaking the game. It does seem like an issue introduced with the patch for the castling bug, however.

**Comment by existentialcomics** [comment]
pretty sure this is resolved now, other bugs are not related to castling
